- name: Deploy common cluster (certs, xqueue, elasticsearch, rabbitmq)
  hosts: ccservers
  sudo: True
  vars_files:
    - "../../../configuration-secure/vars/deployment.yml"
  gather_facts: True
  roles:
    - bdu_common
    - common
    - supervisor
    - bdu_certs
    - certs
    - role: nginx
      nginx_sites:
      - certs
      - xqueue
    - role: xqueue
      update_users: True
    - oraclejdk
    - elasticsearch
    - role: rabbitmq
      rabbitmq_ip: '0.0.0.0'

#
# In order to reconfigure the host resolution we are issuing a
# reboot.
# TODO: We should probably poll to ensure the host comes back before moving
# to the next host so that we don't reboot all of the servers simultaneously
# - hosts: ~{{ machine }}
#   sudo: True
#   serial: 1
#   vars:
#     reboot: False
#   tasks:
#     - name: reboot
#       command: /sbin/shutdown -r now "Reboot is triggered by Ansible"
#       when: reboot
#       tags: reboot
