- name: Deploy edxapp
  hosts: "{{ machine }}"
  pre_tasks:
    - fail: msg="This playbook only runnable on 'app' machines"
      when: "'app' not in machine"
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../../configuration-secure'
    # The default behaviour is not to migrate db
    # migrate_db: yes
    EDXAPP_OEE_URL: 'http://{{ BDU_WORKERS }}:18060/'
    BDU_FIREWALL_ALLOWED_PORTS:
      - "22"
      - "{{ EDXAPP_LMS_NGINX_PORT }}"
      - "{{ EDXAPP_LMS_SSL_NGINX_PORT }}"
      - "{{ EDXAPP_LMS_PREVIEW_NGINX_PORT }}"
      - "{{ EDXAPP_CMS_NGINX_PORT }}"
      - "{{ EDXAPP_CMS_SSL_NGINX_PORT }}"
  vars_files:
    - "{{ secure_dir }}/vars/deployment.yml"
    - "{{ secure_dir }}/vars/keys.yml"
  roles:
    - bdu_common
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - bdu_edxapp
    - forum
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
