- name: Deploy edxapp
  hosts: appservers
  sudo: True
  gather_facts: True
  vars:
    # The default behaviour is not to migrate db
    # migrate_db: yes
    EDXAPP_OEE_URL: 'http://{{ BDU_WORKERS }}:18060/'
    BDU_FIREWALL_ALLOWED_PORTS:
      - "22"
      - "{{ EDXAPP_LMS_NGINX_PORT }}"
      - "{{ EDXAPP_LMS_SSL_NGINX_PORT }}"
      - "{{ EDXAPP_LMS_PREVIEW_NGINX_PORT }}"
      - "{{ EDXAPP_CMS_NGINX_PORT }}"
      - "{{ EDXAPP_CMS_SSL_NGINX_PORT }}"
  vars_files:
    - "../../../configuration-secure/vars/deployment.yml"
  roles:
    - bdu_common
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - bdu_edxapp
    - forum
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
