- name: "Deploy MySQL, MongoDB and memcached"
  hosts: ~{{ machine }}
  pre_tasks:
    - fail: msg="This playbook only runnable on 'db' machines"
      when: "'db' not in machine"
  sudo: True
  vars:
    secure_dir: '../../../configuration-secure'
  vars_files:
    - "{{ secure_dir }}/vars/deployment.yml"
    - "{{ secure_dir }}/vars/keys.yml"
  gather_facts: True
  roles:
    - bdu_common
    - common
    - supervisor
    - bdu_edxlocal
    - mongo
