- name: "Deploy MySQL, MongoDB and memcached"
  hosts: dbservers
  sudo: True
  vars_files:
    - "../../../configuration-secure/vars/keys.yml"
  gather_facts: True
  roles:
    - bdu_common
    - common
    - supervisor
    - mysql
    - mongo
    - bdu_edxlocal
