- name: Deploy worker
  hosts: workerservers
  sudo: True
  vars_files:
    - "../../../configuration-secure/vars/deployment.yml"
  gather_facts: True
  roles:
    - bdu_common
    - role: edxapp
      celery_worker: True
