---

#
# These are the necessary  vars needed to run this role.
#
BDU_DATABASE: ''

EDXAPP_MYSQL_USER: ''
EDXAPP_MYSQL_PASSWORD: ''
EDXAPP_MYSQL_DB_NAME: ''

XQUEUE_MYSQL_USER: ''
XQUEUE_MYSQL_PASSWORD: ''
XQUEUE_MYSQL_DB_NAME: ''

COMMON_MYSQL_MIGRATE_USER: ''
COMMON_MYSQL_MIGRATE_PASSWORD: ''

COMMON_MYSQL_READ_ONLY_USER: ''
COMMON_MYSQL_READ_ONLY_PASS: ''
